### ISSUE TITLE
Incorrect error message on unclosed element after properly closed elements

### ISSUE THREAD

**Issue by theRealProHacker** [syntax-tree/mdast-util-mdx-jsx#12]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

latest version

### Steps to reproduce

This code
```
<A>
<B></B>
```
produces this error

```
1:1: Expected a closing tag for `</B>` (1:1-1:4)
```

Which seems to come from here: https://github.com/syntax-tree/mdast-util-mdx-jsx/blob/bf60d93bdffde6e4d3359324170d438e5ee62a63/lib/index.js#L424-L471

### Expected behavior

I would have expected an error that asks me to close the `<A>` tag/element.

### Actual behavior

The error asks me to close the `</B>` tag, which is itself a closing tag

### Affected runtime and version

node@20.0

**Comment by wooorm** [comment]
Thanks, released in https://github.com/syntax-tree/mdast-util-mdx-jsx/releases/tag/3.1.1!
