### ISSUE TITLE
Yarn v2 error because `unist-util-stringify-position` is not in `package.json`

### ISSUE THREAD

**Issue by dungle-scrubs** [syntax-tree/mdast-util-mdx-jsx#2]
When using Yarn v2, I get the following error:

`Error: mdast-util-mdx-jsx tried to access unist-util-stringify-position, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.`

I can see that `from-markdown.js` has `var stringifyPosition = require('unist-util-stringify-position')`

Should this be added to `package.json`?

**Comment by wooorm** [comment]
Yup, thanks!
