### ISSUE TITLE
Cannot close `mdxJsxTextTag` a different token `paragraph` is open

### ISSUE THREAD

**Issue by ChristianMurphy** [syntax-tree/mdast-util-mdx-jsx#5]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

1.1.2

### Link to runnable example

https://stackblitz.com/edit/node-4jipvc?file=index.js

### Steps to reproduce

run

```js
import * as acorn from 'acorn';
import { fromMarkdown } from 'mdast-util-from-markdown';
import { mdxJsx } from 'micromark-extension-mdx-jsx';
import { mdxJsxFromMarkdown } from 'mdast-util-mdx-jsx';

const content = `<b>
  example
</b> example`;

const tree = fromMarkdown(content, {
  extensions: [mdxJsx({ acorn: acorn, addResult: true })],
  mdastExtensions: [mdxJsxFromMarkdown],
});

console.log(tree);
```

### Expected behavior

A `paragraph`, `mdxJsxFlowElement` and `text` node.

or

a clearer error message.

### Actual behavior

```
Error: Cannot close `mdxJsxTextTag` (3:1-3:5): a different token (`paragraph`, 2:3-3:13) is open
    at async ModuleJob.run (https://node-4jipvc.w.staticblitz.com/blitz.5a55fa0dbb2eb8daf8e20eb3b6ad27ffc8ae4a6b.js:6:734565)
    at async Loader.import (https://node-4jipvc.w.staticblitz.com/blitz.5a55fa0dbb2eb8daf8e20eb3b6ad27ffc8ae4a6b.js:6:865940)
    at async Object.r.loadESM (https://node-4jipvc.w.staticblitz.com/blitz.5a55fa0dbb2eb8daf8e20eb3b6ad27ffc8ae4a6b.js:6:249892)
```

### Runtime

Node v16

### Package manager

npm v7

### OS

Linux

**Comment by ChristianMurphy** [comment]
The version tested includes https://github.com/syntax-tree/mdast-util-mdx-jsx/commit/e6661a63cde8bb7172bac034e7f281406fc7d895, this error does not appear to be covered by those changes.

**Comment by wooorm** [comment]
The error added earlier was for `a *b <c> d* </c>` (so “markdown” closes while a JSX tag is open).
Added an another error for `<a> *b </a> c* d` (JSX closes while markdown is open)
