### ISSUE TITLE
Extraneous indent for mdxJsxTextElements during stringify

### ISSUE THREAD

**Issue by tonywu6** [syntax-tree/mdast-util-mdx-jsx#9]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

mdast-util-mdx-jsx@2.1.3, remark-mdx@2.3.0, remark-parse@10.0.2, remark-stringify@10.0.3

### Link to runnable example

https://codesandbox.io/p/sandbox/nostalgic-cloud-fdvyzk

### Steps to reproduce

Maybe introduced here?

https://github.com/syntax-tree/mdast-util-mdx-jsx/blob/10a502c81764206f031edd71d9799a4da7e3f3d2/lib/index.js#L529

With default options, parse and then stringify a MDX document containing a `mdxJsxTextElement` nested inside a `mdxJsxFlowElement`, for example:

```jsx
<div>
    Lorem ipsum <span>dolor</span> sit amet
</div>
```

### Expected behavior

Input and output should be the same

### Actual behavior

Inline elements have extra whitespace in front of them

```jsx
<div>
    Lorem ipsum   <span>dolor</span> sit amet
</div>
```

### Affected runtime and version

node@16.20

### Affected package manager and version

pnpm@8.5.0

### Affected OS and version

macOS Ventura 13.1

**Comment by wooorm** [comment]
`inferDepth` *only* handles flow elements, not texts: https://github.com/syntax-tree/mdast-util-mdx-jsx/blob/10a502c81764206f031edd71d9799a4da7e3f3d2/lib/index.js#L732.

**Comment by wooorm** [comment]
Can repro in this project, thanks!

**Comment by wooorm** [comment]
Thanks for the report, [released](https://github.com/syntax-tree/mdast-util-mdx-jsx/releases/tag/2.1.4)!
